version: "0.2"
dictionaryDefinitions:
  - name: cspell-dictionary-plex
    path: ./.config/cspell-dictionary-plex.txt
    addWords: true
dictionaries:
  - cspell-dictionary-plex
words: []
ignoreWords: []
import: []
files:
  - "**/*"
ignorePaths:
  - "node_modules/**"
  - ".vscode/**"
  - ".git/**"
  - ".vs/**"
  - ".gdn/**"
useGitignore: true
enableGlobDot: true
