# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

vars:
  RM: '{{if eq .OS "Windows_NT"}}powershell -NoProfile -Command Remove-Item -Recurse -Force {{else}}rm -rf{{end}}'
  OUTPUT_DIRECTORY: "{{.TASKFILE_DIR}}/.build"
  ENV_FILE: "{{.TASKFILE_DIR}}/.env"
  GIT_SUBMODULE: "git submodule foreach"
  PROTO: "{{.USERPROFILE}}/.proto/bin/proto.exe"
  BUILD_DIR: "{{.ROOT_DIR}}/.build/task"
  DATE: '{{if eq .OS "Windows_NT"}}cmd /d /c "powershell -noprofile get-date -format ^"{yyyy-MM-dd HH:mm:ss}^""{{else}}date{{end}}'

tasks:
  default:
    cmds:
      - task: build

  setup:
    deps: [setup-git, setup-proto, setup-dotnet]

  setup-proto:
    cmds:
      - cmd: proto use
        silent: true
        ignore_error: true

  setup-git:
    cmds:
      - cmd: git config --global submodule.recurse true
      - cmd: git submodule update --init --recursive --checkout

  setup-dotnet:
    cmds:
      - cmd: dotnet tool restore

  clean:
    cmds:
      - cmd: git add .
      # - cmd: git clean -xfd 2>&1 >nul <nul
      - cmd: git clean -xfd

  build:
    deps: [setup]
    cmds:
      - task: clean
      - task: build-project
        vars:
          PROJECT_PATH: "PlexServiceCommon/"
      - task: build-project
        vars:
          PROJECT_PATH: "PlexService/"
      - task: build-project
        vars:
          PROJECT_PATH: "PlexServiceTray/"
      - task: build-project
        vars:
          PROJECT_PATH: "PlexServiceWCF/"
      - task: build-project
        vars:
          PROJECT_PATH: "PlexServiceInstaller/"

  spellcheck:
    deps: [setup]
    cmds:
      - cmd: npx --yes cspell-cli@latest .

  build-project:
    internal: true
    preconditions:
      - test -d "{{.PROJECT_PATH}}/"
    cmds:
      - cmd: dotnet restore --locked-mode --runtime win-x64 "{{.PROJECT_PATH}}"
      - cmd: dotnet build --no-restore --os win --arch x64 --configuration "Release" "{{.PROJECT_PATH}}"
